# Generated by Django 5.1.7 on 2025-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article_created_at',
            field=models.DateTimeField(),
        ),
    ]
