# Generated by Django 5.1.7 on 2025-03-19 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_news_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
