# Generated by Django 5.1.7 on 2025-03-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_news_article_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['article_created_at']},
        ),
    ]
