# Generated by Django 5.1.7 on 2025-03-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-article_created_at']},
        ),
    ]
