# Generated by Django 5.1.7 on 2025-04-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_songs_file_alter_songs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
