# Generated by Django 5.1.7 on 2025-04-10 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('text', models.TextField(blank=True)),
                ('doc_file', models.FileField(upload_to='documents/')),
                ('article_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-article_created_at'],
            },
        ),
    ]
