# Generated by Django 5.1.7 on 2025-04-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='tune_type',
            field=models.CharField(blank=True, choices=[('Jig', 'Jig'), ('Reel', 'Reel'), ('Polka', 'Polka'), ('Listening_Tune', 'Listening_Tune')], default=None, max_length=20, null=True),
        ),
    ]
