# Generated by Django 5.1.7 on 2025-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_songs_tune_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='is_set',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='tune_type',
            field=models.TextField(blank=True, choices=[(1, 'Jig'), (2, 'Reel'), (3, 'Polka'), (4, 'Listening_Tune')], default=None, max_length=20, null=True),
        ),
    ]
