# Generated by Django 5.1.7 on 2025-04-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_songs_is_set_alter_songs_tune_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='tune_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Jig'), (2, 'Reel'), (3, 'Polka'), (4, 'Listening_Tune')], default=None, null=True),
        ),
    ]
