# Generated by Django 5.1.7 on 2025-04-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_songs_tune_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='tune_type',
            field=models.IntegerField(blank=True, choices=[(1, 'N/A'), (2, 'Jig'), (3, 'Reel'), (4, 'Polka'), (5, 'Listening_Tune')], default=None, null=True),
        ),
    ]
