# Generated by Django 5.1.7 on 2025-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_songs_tune_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='moderator',
            field=models.CharField(blank=True, default=False, max_length=3, null=True),
        ),
    ]
