# Generated by Django 5.1.7 on 2025-04-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_customuser_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='moderator',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
    ]
