# Generated by Django 5.1.7 on 2025-04-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_songs_tune_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='tune_type',
            field=models.CharField(blank=True, choices=[(1, 'N/A'), (2, 'Jig'), (3, 'Reel'), (4, 'Polka'), (5, 'Listening_Tune')], default='N/A', max_length=25, null=True),
        ),
    ]
