# Generated by Django 5.1.7 on 2025-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_songs_tune_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='tune_type',
            field=models.CharField(choices=[(1, 'N/A'), (2, 'Jig'), (3, 'Reel'), (4, 'Polka'), (5, 'Listening_Tune')], max_length=25),
        ),
    ]
