# Generated by Django 5.1.7 on 2025-04-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_songs_tune_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='is_set',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='moderated',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default=False, max_length=5, null=True),
        ),
    ]
