# Generated by Django 5.1.7 on 2025-04-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_songs_is_set_alter_songs_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='is_set',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Yes')], default=False, max_length=5, null=True),
        ),
    ]
