# Generated by Django 5.1.7 on 2025-05-14 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_songs_is_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setTitle', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('setDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-setDate'],
            },
        ),
        migrations.CreateModel(
            name='SetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.set')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.songs')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
