# Generated by Django 5.1.7 on 2025-05-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_set_setlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danceName', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'ordering': ['danceName'],
            },
        ),
        migrations.AddField(
            model_name='setlist',
            name='dance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.dances'),
            preserve_default=False,
        ),
    ]
