# Generated by Django 5.1.7 on 2025-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_dances_options_setlist_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='gigdate',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
