# Generated by Django 5.1.7 on 2025-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_setlist_gigdate_setlist_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
