# Generated by Django 5.1.7 on 2025-11-15 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_remove_setlist_gigdate_remove_setlist_venue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('content_text', models.TextField(blank=True)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('article_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-article_created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['article_created_at']},
        ),
    ]
