# Generated by Django 5.2.8 on 2025-12-14 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_testimonials_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
